### PR TITLE
Expose the raw trie object on the class instance

### PR DESCRIPTION
**Pull request by arjunmehta**

### CODE REVIEW

**Comment by arjunmehta** [comment]
Fixes https://github.com/lyndseybrowning/trie-prefix-tree/issues/3

**Comment by lyndseybrowning** [comment]
Thank you!

**Comment by arjunmehta** [comment]
@lyndseybrowning Awesome! Thank YOU! Any chance this would get published to npm sometime soon?

**Comment by lyndseybrowning** [comment]
Sure, I'll update the README and get an update out ASAP.

**Comment by arjunmehta** [comment]
Awesome! Thank you so much!

**Comment by lyndseybrowning** [comment]
All done.

**Comment by arjunmehta** [comment]
👍 🥇 
Woo. Thanks again!

**Pull request merged**
